---
title: "Basic Graphs"
author: "Hyeongjin Joo"
date: "2023-01-14"
output:
  pdf_document:
    latex_engine: xelatex
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 예제1

## 자료 입력
```{r}
death <- c(2,1,2,4,2,5,3,3,5,6,3,8,3,
           3,6,3,6,5,3,5,2,6,2,3,4,3,
           2,9,2,2,3,2,7,3,2,10,6,2,3,
           1,2,3,3,4,3,2,6,2,2,3,2,3,
           4,3,2,3,5,2,5,5,3,4,3,6,2,
           1,2,3,2,6,3,3,6,3,2,3,6,4,
           6,5,3,5,6,2,6,3,2,3,2,6,2,
           6,3,3,2,6,9,6,3,6,6,2,3,2,
           3,5,3,5,2,3,2,3,3,1,3,3,2,
           3,3,4,3,6,6,3,3,3,2,3,3,6)

```

## 도수분포표
```{r}
table(death)
# 3가 제일 많이 발생하고 2가 두번째로 발생하는 것을 
# 알 수 있다. 1, 7, 8, 9, 10 have small 
# frequency.
```

## 막대그래프 그리기
```{r}

freq.table<-table(death)

cause<-c("감염성 질환", "각종 암", 
      "순환기 질환", " 호흡기 질환",
      "소화기 질환","각종 사고사", 
      "비뇨기 질환", "정신병","노환", 
      "신경계 질환")

barplot(freq.table, col=rainbow(10),
        main="사망원인에 대한 막대그래프",
        ylab="빈도수", xlab="사망원인",
        legend.text=cause,
        args.legend=list(x="topright"))
```

## 원형그래프
```{r}
pie(freq.table,label=cause,
        main="사망원인에 대한 원형그래프",
        cex=0.7)
```

## 파레토 그래프
```{r message=FALSE}
# install.packages("qcc")
library(qcc)
pareto.chart(freq.table,
             main="사망원인에 대한 파레토그림",
             xlab="질병종류",
             ylab="도수",ylab2="누적상대도수",
             legend.text=cause)
# 3(순환기 질환), 2(각종 암), 6(사고사)가
# 전체 사망의 80% 가까이 차지하고 있는 것을
# 알 수 있다.
```
***

# 예제2

## 자료입력
```{r}
drink <- c(101.8,101.5,101.8,102.6,101,96.8,102.4,100,98.8,98.1,
           98.8,98,99.4,95.5,100.1,100.5,97.4,100.2,101.4,98.7,
           101.4,99.4,101.7,99,99.7,98.9,99.5,100,99.7,100.9,
           99.7,99,98.8,99.7,100.9,99.9,97.5,101.5,98.2,99.2,
           98.6,101.4,102.1,102.9,100.8,99.4,103.7,100.3,100.2,101.1,
           101.8,100,101.2,100.5,101.2,101.6,99.9,100.5,100.4,98.1,
           100.1,101.6,99.3,96.1,100,99.7,99.7,99.4,101.5,100.9,
           101.3,99.9,99.1,100.7,100.8,100.8,101.4,100.3,98.4,97.2)
```

## 히스토그램램
```{r}
hist(drink, freq=F)
hist.result<-hist(drink, freq=F)
lines(x=hist.result$mids,
      y=hist.result$density,
      type="b",
      pch=20)
# 단봉형으로 오른쪽으로 약간 쏠린 것으로 
# 보이나 쏠린 정도가 심한 것 같지는 않다.
# 데이터가 100 중심으로 나타난 것 같다.
```

## 기술통계량량
```{r}
summary(drink)
var(drink)
sd(drink)
IQR(drink)

# PKG
# install.packages("psych")
library(psych)
describe(drink)
```


# 예제3

## 자료입력
```{r}
height <- c(181,161,170,160,158,168,162,179,183,178,171,177,163,158,160,160,158,
            173,160,163,167,165,163,173,178,170,167,177,175,169,152,158,160,160,
            159,180,169,162,178,173,173,171,171,170,160,167,168,166,164,173,180)
weight <- c(78,49,52,53,50,57,53,54,71,73,55,73,51,53,65,48,59,
            64,48,53,78,45,56,70,68,59,55,64,59,55,38,45,50,46,
            50,63,71,52,74,52,61,65,68,57,47,48,58,59,55,74,74)
```

## Dot plot 확인
```{r}
plot(x=height, y=weight,xlab="키(cm)",
	ylab="몸무게(kg)",
	main="키와 몸무게 산점도", pch=16)

# 키가 증가할수록 몸무게가 증가하는 경향이 있다.
# 직선의 경향을 보이지만 좀 퍼져 있는 패턴이 
# 있는 것으로 보인다.
```

## Correlation
```{r}
cor(height,weight)
cor.test(height,weight)
# 상관계수가 0.74로 양의 선형관계를 나타내는 
# 것을 알 수 있다. p-value가 매우 작으므로
# 직선의 관계가 있다는 것을 알 수 있다.
```

